apiVersion: v1
kind: Pod
metadata:
  name: get-data
spec:
  containers:
    - image: fbraza/get-data:v1
      name: get-data
      volumeMounts:
        - mountPath: /tmp/data
          name: data
      args:
        - /bin/sh
        - -c
        - 'kaggle datasets download lava18/google-play-store-apps -F /tmp/data'
      env:
        - name: KAGGLE_USERNAME
          valueFrom:
              secretKeyRef:
                key: username
                name: kaggle-api
        - name: KAGGLE_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: kaggle-api
  volumes:
    - name: data
      emptyDir: {}
